### ISSUE TITLE
Left align posts

### ISSUE THREAD

**Issue by iborghoff** [brennanbrown/purelog#6]
Thanks for the really nice clean theme :)

I had a question regarding posts - Is it possible to align these to the left as the home page is?

**Comment by brennanbrown** [comment]
Hi, thanks!

Yes, there is. In `assets/main.css` at line `222`: 

```css
.post-body p,
.post-body li {
  font-size: 16px;
  text-align: justify;
  line-height: 1.5;
}
```

Delete the `text-align` property at line `225`.
